apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitnode.fullname" . }}
  labels:
    {{- include "bitnode.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bitnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bitnode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bitnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: create-certificates
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - cp 
            - "-av"
            - /data/certificates/.
            - /root/.btcd/
          volumeMounts:
            - name: home
              mountPath: /root/.btcd
            - name: config
              mountPath: /data/certificates
      containers:
        - name: btcd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-C"
            - "/etc/btcd/btcd.conf"
            - "--datadir"
            - "/btcd"
{{- if .Values.regtest }}            
            - "--regtest"
{{- end }}            
{{- if .Values.miningaddr }}            
            - "--miningaddr"
            - {{.Values.miningaddr}}
{{- end }}       
          ports:
            - name: rpc
              containerPort: {{ include "rpcPort" . }}
            - name: p2p
              containerPort: {{ include "p2pPort" . }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /btcd
            - name: config
              mountPath: /etc/btcd/btcd.conf
              subPath: btcd.conf
            - name: home
              mountPath: /root/.btcd
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "bitnode.fullname" . }}
        - name: home
          emptyDir: {}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitnode.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}            