apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitnode.fullname" . }}
  labels:
    {{- include "bitnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ include "rpcPort" . }}
      targetPort: rpc
    - name: p2p
      port: {{ include "p2pPort" . }}
      targetPort: p2p
  selector:
    {{- include "bitnode.selectorLabels" . | nindent 4 }}
