{{- if .Values.btcRpcExplorer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitnode.fullname" . }}-rpc-explorer
  labels:
    {{- include "bre.labels" . | nindent 4 }}
spec:
  {{- with .Values.btcRpcExplorer }}
  type: {{ .service.type }}
  ports:
    - name: http
      port: {{ .service.port }}
      targetPort: http
  {{- end }}
  selector:
    {{- include "bre.selectorLabels" . | nindent 4 }}
{{- end }}